---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/authors":
    get:
      summary: list authors
      responses:
        '200':
          description: successful
    post:
      summary: create author
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                main_gender:
                  type: string
                age:
                  type: string
  "/authors/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show author
      responses:
        '200':
          description: successful
        '404':
          description: Not Found
    patch:
      summary: update author
      parameters: []
      responses:
        '200':
          description: successful
        '404':
          description: Not Found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                main_gender:
                  type: string
                age:
                  type: string
    put:
      summary: update author
      parameters: []
      responses:
        '200':
          description: successful
        '404':
          description: Not Found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                main_gender:
                  type: string
                age:
                  type: string
    delete:
      summary: delete author
      responses:
        '200':
          description: successful
        '404':
          description: Not Found
  "/books":
    get:
      summary: list books
      responses:
        '200':
          description: successful
    post:
      summary: create book
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                gender:
                  type: string
                author_id:
                  type: integer
                publish_date:
                  type: datetime
                publishing_company:
                  type: string
  "/books/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show book
      responses:
        '200':
          description: successful
        '404':
          description: Not Found
    patch:
      summary: update book
      parameters: []
      responses:
        '200':
          description: successful
        '404':
          description: Not Found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                gender:
                  type: string
                author_id:
                  type: integer
                publish_date:
                  type: datetime
                publishing_company:
                  type: string
    put:
      summary: update book
      parameters: []
      responses:
        '200':
          description: successful
        '404':
          description: Not Found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                gender:
                  type: string
                author_id:
                  type: integer
                publish_date:
                  type: datetime
                publishing_company:
                  type: string
    delete:
      summary: delete book
      responses:
        '200':
          description: successful
        '404':
          description: Not Found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
